### ISSUE TITLE
Hide when it's only one tab page

### ISSUE THREAD

**Issue by podratz** [crispgm/nvim-tabline#10]
It would be nice to have an option that allows to hide the tab bar when only one tab page is open.
That's the default vim behaviour and I'd prefer it that way.

**Comment by crispgm** [comment]
@nickpodratz sounds like it is supported by option: https://github.com/crispgm/nvim-tabline/pull/5

**Comment by podratz** [comment]
I'll have a look later, thanks!

**Comment by minghongx** [comment]
I think this line can be deleted to restore to the default behaviour.
https://github.com/crispgm/nvim-tabline/blob/7044c5b73678c7b0161f4c37acd0f555cc3ce908/lua/tabline.lua#L89

**Comment by podratz** [comment]
Ok thanks!
