### ISSUE TITLE
brackets in name

### ISSUE THREAD

**Issue by ghost** [crispgm/nvim-tabline#3]
Hi, Please add an option to remove brackets in names. Thanks
Note: I added the bracket_character = false, but it did not worked. Then tried bracket_in_name and it failed also. Please fix.
![Screenshot at 2022-07-28 03-47-24](https://user-images.githubusercontent.com/108426549/181450763-14873519-05b7-4f23-bce7-9646bae2dc78.png)

**Comment by crispgm** [comment]
@spelb Hi, that feature is under review. I will merge ASAP it finished reviewing. Thanks.

**Comment by ghost** [comment]
> @spelb Hi, that feature is under review. I will merge ASAP it finished reviewing. Thanks.

Okay Thank you

**Comment by crispgm** [comment]
@ghost This is supported by 4d023b84eb3e6ff63afec8400fa541e6bfe6ac20 with `brackets` option.
Please add the following option:
```lua
require('tabline').setup({
    brackets = { '', '' },
})
```
