### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ntanhpro1221** [crispgm/nvim-tabline#4]
Hello,i added it in my init.vim but nothing happen
-Init.vim:

set number
set mouse=a

call plug#begin('C:\Users\Ntanh\AppData\Local\nvim\autoload\plugged')

"-----------------<{FOR_FAST_CODING}>-------------------
Plug 'gosukiwi/vim-smartpairs'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"-----------------<{FILE_MANAGEMENT}>--------------------
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
"-----------------<{STATUS_BAR}>--------------------
"Plug 'itchyny/lightline.vim'
"Plug 'mengelbrecht/lightline-bufferline'
"Plug 'Ap/vim-buftabline'
Plug 'crispgm/nvim-tabline'
"---------------------<{THEME}>-------------------------
Plug 'tanvirtin/monokai.nvim'

call plug#end()
colorscheme monokai_pro

"---------------------<{COPY_PATE}>-------------------------
vmap <C-c> "+y

"---------------------<{EXTENDED_SETTINGS}>-------------------------
let nvim_settings_dir = 'C:\Users\Ntanh\AppData\Local\nvim\settings\'
execute 'source '.nvim_settings_dir.'_nerdtree.vim'
execute 'source '.nvim_settings_dir.'_airline.vim'

I dont know what im missing.thanks

**Comment by crispgm** [comment]
Would you mind please providing your Neovim version and OS platform?

**Comment by crispgm** [comment]
You may need to setup before use:
```lua
require('tabline').setup()
```
