### ISSUE TITLE
docu: fix length instead of len

### ISSUE THREAD

**Issue by michaelrommel** [crispgm/nvim-tabline#8]
Hi,
I really like this minimal module. Two things I noticed:

1. The example states the opt `inactive_tab_max_len`, but in the code it really is `inactive_tab_max_length`
2. I think about an option to prepend the title with an abbreviated unique path name, much like some of the zsh prompts, e.g. `p/init.lua` and `c/init.lua` to distinguish between two open buffers from the core or plugins directory...

Thanks,

  Michael.

**Comment by michaelrommel** [comment]
Damn, I wanted to open a PR with the small modifications, which I adapted from cokeline, but now my autoformatter has converted all the indents to tabs... I am sure you would not want that. (I recently switched to tab indents, because of accessibility reasons with braille terminals - and that was the first and only reason I heard in years, that was valid).

If you want to have a look, the forked version is here and there is basically only one function and then three additional changed lines:

https://github.com/michaelrommel/nvim-tabline

Maybe you like that... thanks for your inspiration!

Michael.

**Comment by crispgm** [comment]
> 1. The example states the opt `inactive_tab_max_len`, but in the code it really is `inactive_tab_max_length`

This is fixed. Thanks for the issue.

> 2. I think about an option to prepend the title with an abbreviated unique path name, much like some of the zsh prompts, e.g. `p/init.lua` and `c/init.lua` to distinguish between two open buffers from the core or plugins directory...

Good idea. I guess we need an option based on `:help fnamemodify`.

**Comment by crispgm** [comment]
@michaelrommel `fnamemodify` is supported now. You may update the latest to try it on. :)
